[package]
name = "RustRayTracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.test]
opt-level = 0

[dependencies]
image = "0.24.6"
libmath = "0.2.*"
rand = "0.8.*"
lazy_static = "1.4.*"

